#!/usr/bin/env bash

###         notes          ###
### A script by @sevenpkgs ###

# A simple notes program using fzf #


pushd "$HOME/Documents/notes"
 
#NOTE=$(date +%d\ %b\ %Y,\ %R)
NOTE=$(date +%d-\%b-\%Y\ %H\;\%M)
 
FZF_DEFAULT_COMMAND="ls *.md | sort -t' ' -k1,1 -k2,2 -k3,3 -k4,4 | sort -k1.8,1.11 -k1.4,1.5 -k1.1,1.2 -k2.1,2.3 -r" \
  fzf --height=100% --preview-window=right:75%:wrap \
  --preview 'bat --language=md --style=plain --theme=gruvbox-dark --color=always {}' \
  --bind 'enter:execute(nvim {})' \
  --bind 'ctrl-r:reload(bash -c "$FZF_DEFAULT_COMMAND")' \
  --bind 'ctrl-x:execute-silent(rm -f {})+reload(bash -c "$FZF_DEFAULT_COMMAND")' \
  --bind "ctrl-i:execute(nvim \"${NOTE}.md\")" \
  --bind 'ctrl-f:execute(bash ./search.sh)'
popd
